
---
# namespace для приложений
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    istio-injection: enable

# настройка инъекций istio
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    istio-injection: disabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: jaeger-operator
  labels:
    istio-injection: disabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: kiali-operator
  labels:
    istio-injection: disabled
